services:
  - type: web
    name: flask-docker-app
    env: docker
    plan: free
    region: oregon
    dockerfilePath: Dockerfile
    branch: master
    repo: https://github.com/Aswinchacko/Python-FLask-Web-App-for-Exploratory-Data-Analysis.git
